### ISSUE TITLE
global position of ui element

### ISSUE THREAD

**Issue by sebastienjouhans** [pixijs/pixi-ui#48]
I am trying to get the position (x,y) of a ui element (button, text, etc) so i can work out when a virtual pointer collided with it.

I can easily get the width and the height of any ui elements but the x,y do not seem to be exposed.

1) Is there a way to get the x and y coordinate of a ui element?
2) is there a way to perform a hit test?

**Comment by SukantPal** [comment]
@sebastienjouhans I don't think `Widget` exposes the global (x, y) coordinates because it itself doesn't track them. What you _can_ get is the local (x,y) coordinates using the layout measure.

https://github.com/pixijs/pixi-ui/blob/5971dde42d3bf09eb635972d02790d8d997a46b2/packages/core/src/Widget.ts#L61

which is

https://github.com/pixijs/pixi-ui/blob/5971dde42d3bf09eb635972d02790d8d997a46b2/packages/core/src/layout-options/Insets.ts#L5

You can also use `insetContainer` to get the _world_ bounds of the widget's contents (+ any padding you applied, use `contentContainer` for without padding).

https://github.com/pixijs/pixi-ui/blob/5971dde42d3bf09eb635972d02790d8d997a46b2/packages/core/src/Widget.ts#L41

via

```
widget.insetContainer.getBounds()
```

Hit testing is not done in this project. That's because it uses the interaction events fired on the insetContainer, which is done by PixiJS out-of-the-box.

**Comment by sebastienjouhans** [comment]
That worked! thanks

One more thing, is there a way to programmatically invoke for instance the button mouse click method?

What I have tried so far does not seem to work.

**Comment by sebastienjouhans** [comment]
That worked! thanks

**Comment by SukantPal** [comment]
@sebastienjouhans My bad that this repo is in sort of a "dumb frozen" state. The current code has some stuff that is in a transitionary phase so it won't reflect what's published.

The published API uses EventBroker:

https://github.com/pixijs/pixi-ui/blob/5971dde42d3bf09eb635972d02790d8d997a46b2/packages/core/src/Widget.ts#L521

which is here:

https://github.com/pixijs/pixi-ui/blob/5971dde42d3bf09eb635972d02790d8d997a46b2/packages/core/src/event/EventBroker.ts#L15

It has a click manager: 

https://github.com/pixijs/pixi-ui/blob/5971dde42d3bf09eb635972d02790d8d997a46b2/packages/core/src/event/ClickManager.ts#L175

It might work if you fire a `mousedown`, `mouseup` event manually on the `insetContainer`:

```js
insetContainer.fire('mousedown', <your_fake_event>);
```

**Comment by SukantPal** [comment]
Ah, nvm you deleted that comment. I can help you if you're working on something that needs help 👍
